# Generated by Django 5.1.3 on 2024-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='associated_pos',
            field=models.CharField(blank=True, help_text='Associated POS system with the restaurant', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='kitchen_closing_time',
            field=models.TimeField(blank=True, help_text='Kitchen closing time', null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='organised_seating',
            field=models.BooleanField(default=False, help_text='Check if the restaurant has organised seating'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_details',
            field=models.TextField(blank=True, help_text="Owner's Contact Details", null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(blank=True, help_text="Owner's Name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='parcel_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Parcel charges for takeaway orders', max_digits=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='publicly_accessible',
            field=models.BooleanField(default=True, help_text='Check if the restaurant is publicly accessible'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='seating_capacity',
            field=models.PositiveIntegerField(default=0, help_text='Number of seats available for dine-in customers'),
        ),
    ]
