# Generated by Django 5.1.3 on 2024-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_associated_pos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='parcel_charges',
            new_name='base_parcel_charges',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='additional_parcel_charges',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Additional Parcel charges per item for takeaway orders', max_digits=10),
        ),
    ]
