# Generated by Django 5.1.3 on 2024-12-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_rename_parcel_charges_restaurant_base_parcel_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
            ],
            options={
                'verbose_name': 'Item Availability',
                'verbose_name_plural': 'Item Availabilities',
                'ordering': ['weekday'],
            },
        ),
        migrations.RemoveField(
            model_name='customizationgroup',
            name='options_allowed',
        ),
        migrations.AddField(
            model_name='customizationgroup',
            name='max_options_allowed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customizationgroup',
            name='min_options_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='spice_level',
            field=models.PositiveIntegerField(choices=[(1, 'Mild'), (2, 'Medium'), (3, 'Spicy')], default=1, help_text='Select the spice level for this menu item (1 = Mild, 2 = Medium, 3 = Spicy)'),
        ),
        migrations.AddField(
            model_name='customizationoption',
            name='sweetness_level',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text='Select the sweetness level for this menu item (1 = Low, 2 = Medium, 3 = High)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='must_try',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='spice_level',
            field=models.PositiveIntegerField(choices=[(1, 'Mild'), (2, 'Medium'), (3, 'Spicy')], default=1, help_text='Select the spice level for this menu item (1 = Mild, 2 = Medium, 3 = Spicy)'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='sweetness_level',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text='Select the sweetness level for this menu item (1 = Low, 2 = Medium, 3 = High)'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='service_style',
            field=models.CharField(choices=[('BUFFET', 'Buffet'), ('SELF_SERVICE', 'Self Service'), ('TABLE_SERVICE', 'Table Service')], default='SELF_SERVICE', help_text='Select the restaurant serving style', max_length=20),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='availability_times',
            field=models.ManyToManyField(blank=True, help_text='Select the availability times for this menu item', related_name='menu_items', to='restaurants.itemavailability'),
        ),
    ]
