# Generated by Django 5.1.3 on 2024-12-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_rename_phone_number_restaurant_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='is_open',
            new_name='is_online',
        ),
    ]
