# Generated by Django 5.1.3 on 2024-12-02 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile_number',
            new_name='phone_number',
        ),
    ]
