# Generated by Django 5.1.3 on 2024-12-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorite_restaurants',
        ),
    ]
