# Generated by Django 5.1.3 on 2024-12-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('restaurant_admin', 'Restaurant Admin'), ('boh_staff', 'BOH Staff'), ('manager', 'Manager'), ('foh_staff', 'FOH Staff'), ('receptionist', 'Receptionist'), ('customer', 'Customer')], default='receptionist', max_length=20),
        ),
    ]
