# Generated by Django 5.1.3 on 2024-12-21 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0006_restaurant_is_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for the order', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment status of the order', max_length=10)),
                ('order_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PREPARING', 'Preparing'), ('READY', 'Ready for Pickup/Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='RECEIVED', help_text='Current status of the order', max_length=10)),
                ('special_instructions', models.TextField(blank=True, help_text='Additional instructions from the customer', null=True)),
                ('delivery_address', models.TextField(blank=True, help_text='Address for delivery (optional for dine-in)', null=True)),
                ('delivery_latitude', models.FloatField(blank=True, help_text='Delivery latitude coordinate', null=True)),
                ('delivery_longitude', models.FloatField(blank=True, help_text='Delivery longitude coordinate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the order was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated time of the order')),
                ('customer', models.ForeignKey(help_text='The user who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(help_text='Restaurant associated with the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of the item ordered')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the item at the time of order', max_digits=10)),
                ('customizations', models.ManyToManyField(blank=True, help_text='Customizations applied to the item', related_name='order_items', to='restaurants.customizationoption')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurants.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(help_text='Menu items in the order', related_name='orders', through='orders.OrderItem', to='restaurants.menuitem'),
        ),
    ]
