# Generated by Django 5.1.3 on 2024-12-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurants', '0009_itemavailability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customizations',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(help_text='Menu item in the order', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='restaurants.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='Order to which this item belongs', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customizations',
            field=models.TextField(blank=True, help_text='Customizations applied to the item', null=True),
        ),
    ]
