# Generated by Django 5.1.3 on 2024-12-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='customizations',
        ),
    ]
