# Generated by Django 5.1.3 on 2024-12-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_created_at_orderitem_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='uuid',
        ),
    ]
